[package]
name = "learn_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"